name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps : 
      - name : Install private SSH Key 
        uses : shimataro/ssh-key-action@v2 
        with : 
          key : ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts : ${{ secrets.SSH_KNOW_HOST }}
          config : ${{ secrets.CONFIG }}
          if_key_exists: fail 
      - name : Pull
        run : | 
          ssh user@x.x.x.x '
          cd /home/user/weathergilannt
          /usr/bin/git pull origin main 
          /usr/bin/nohup /usr/bin/python3 /home/user/weathergilannt/index.py > /dev/null 2>&1 &'